# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='category',
            field=models.IntegerField(default=1),
        ),
    ]
